Homework7(virtual function)
cAfton/GIT pull request #26
Opened 2024-11-07 20:59 UTC by cAfton

2024-11-15 20:45 UTC, Yurii-Vipshovsky requested changes

2024-11-15 20:45 UTC, Yurii-Vipshovsky commented on homeworks/Homework7/VirtualFunction/VirtualFunction.cpp
> +    //FileDuoble workWithFilesDouble;
Треба дописати ще якийсь клас нащадок, виведення у вигляді бінарного було б добре

2024-11-15 20:53 UTC, cAfton commented on homeworks/Homework7/VirtualFunction/VirtualFunction.cpp
> +    //FileDuoble workWithFilesDouble;
цю частину завдання виконує Назар

2024-12-07 06:53 UTC, Yurii-Vipshovsky commented on homeworks/Homework7/VirtualFunction/VirtualFunction.cpp
> +    //FileDuoble workWithFilesDouble;
здається не виконує..

2024-12-07 07:16 UTC, cAfton commented on homeworks/Homework7/VirtualFunction/VirtualFunction.cpp
> +    //FileDuoble workWithFilesDouble;
:(

2025-01-11 17:35 UTC, merged