Homework8(shapes)
cAfton/GIT pull request #29
Opened 2024-11-14 23:42 UTC by cAfton

2024-11-15 20:54 UTC, Yurii-Vipshovsky requested changes

2024-11-15 20:54 UTC, Yurii-Vipshovsky commented on homeworks/Homework8/Shapes/Paralelogram.h
> +		file << this->SideA << endl;
Знов реалізація в хедер файлі

2024-11-15 20:54 UTC, Yurii-Vipshovsky commented on homeworks/Homework8/Shapes/Circle.h
> +	int Y;
Чого ж координати є тільки у кола?

2024-11-29 20:23 UTC, Yurii-Vipshovsky commented on homeworks/Homework8/Shapes/Circle.h
> -	int X;
А чого в кола тепер нема координат??

2024-12-08 14:03 UTC, cAfton commented on homeworks/Homework8/Shapes/Circle.h
> -	int X;
тепер є

2025-01-19 16:37 UTC, merged